### ISSUE TITLE
jinxing\admin\Admin是不是打错了

### ISSUE THREAD

**Issue by abeaczg** [myloveGy/yii2-admin#1]
1.
return [
    'modules' => [
        'admin' => [
            'class' => 'jinxing\admin\Admin',
            是不是应该改成jinxing\admin\Models
....

**Comment by myloveGy** [comment]
1. 是写错啦，正确的配置是：
```
return [
    'components' => [
        'modules' => [
            'admin' => [
                'class' => 'jinxing\admin\Module',
                
                // Make use of that kind of user
                'user' => 'admin'
            ]
        ],
        // authority management
        'authManager'  => [
            'class' => 'yii\rbac\DbManager',
        ],
        ...
    ],
]
```
2. backend\controllers 里的控制器只有那么几个，其他在引入的 jinxing/yii2-admin 包里面，将主要的功能都放到包里面去了，backend\controllers 里面的控制器，只是一个示例,怎么用 jinxing/yii2-admin;
