### ISSUE TITLE
如何获取checkbox选中的值，为什么没有，这么垃圾

### ISSUE THREAD

**Issue by hyyky** [myloveGy/yii2-admin#11]
如何获取checkbox选中的值，为什么没有，这么垃圾
![image](https://user-images.githubusercontent.com/50724513/207263715-776f2a63-b853-43a8-aee0-83c5376f47d0.png)

**Comment by myloveGy** [comment]
![image](https://user-images.githubusercontent.com/11523869/207276500-9b77aabf-62c3-418f-b991-5890a8bd4659.png)

yan can you up, no can no bb
