### ISSUE TITLE
同一页面如果想配置多个metable怎么操作？

### ISSUE THREAD

**Issue by sumic** [myloveGy/yii2-admin#2]
尝试了下，只能初始化最后一个metable，不知道怎么回事。id,name都是重新定义的不同的。

**Comment by myloveGy** [comment]
目前不支持多个表格，内部js实现问题！第二个表格直接使用 jquery.datatables实现吧

**Comment by sumic** [comment]
有办法改吗？风格不统一有点丑呢。

**Comment by myloveGy** [comment]
风格是一致的，databtables 的配置和meTables 里面的配置保持一致就好了！你要改的话，就改meTables 里面的信息
```
// dataTables 表格默认配置对象信息
            table: {
                // "fnServerData": fnServerData,		// 获取数据的处理函数
                // "sAjaxSource":      "search",		// 获取数据地址
                "bLengthChange": true, 			// 是否可以调整分页
                "bAutoWidth": false,           	// 是否自动计算列宽
                "bPaginate": true,			    // 是否使用分页
                "iDisplayStart": 0,
                "iDisplayLength": 10,
                "bServerSide": true,		 	// 是否开启从服务器端获取数据
                "bRetrieve": true,
                "bDestroy": true,
                // "processing": true,		    // 是否使用加载进度条
                // "searching": false,
                "sPaginationType": "full_numbers"     // 分页样式
                // "order": [[1, "desc"]]       // 默认排序，
                // sDom: "t<'row'<'col-xs-6'li><'col-xs-6'p>>"
            },
```

**Comment by sumic** [comment]
我的意思是能不能改成支持多个metable，就是你说的内部JS的问题。问题在哪儿可以讲一下吗？是js本身的限制还是程序写的结构？

**Comment by myloveGy** [comment]
就是metable.js 有问题，不能实例化两个table, 但具体问题出在哪里，我就不太清楚了,应该是我js 写的有问题！因为我js 水平有限，目前没有找到具体原因

**Comment by myloveGy** [comment]
问题可能是js 闭包作用域问题，我测试过，实例化两个的时候，后者会覆盖前者的配置，导致只有一个生效

**Comment by sumic** [comment]
似乎是闭包this指向的问题

**Comment by sumic** [comment]
var name = "The Window";
var object = {
    name: "My object",
    getNameFunc: function() {
        return function() {
            return this.name;
        };
    }
}
alert(object.getNameFunc()()); // "The Window"

**Comment by sumic** [comment]
试试用ts来写，我也才开始看ts,ts默认就支持类，抽象方法。

**Comment by ruithink8** [comment]
左边的菜单栏全都打不开是哪里的问题呢？

**Comment by myloveGy** [comment]
@sumic 最新版，已经支持实例化两个 meTables

**Comment by myloveGy** [comment]
@ruithink8 需要具体问题描述，或者你在 群里截图说明！ 讨论QQ群：697549103
