### ISSUE TITLE
bower-asset/jinxing-tables ~1.0.0 -> no matching package found.

### ISSUE THREAD

**Issue by GordonHuangYong** [myloveGy/yii2-admin#5]
[root@672789358c77 shipping.alberlia.ltd]# /www/server/php/73/bin/php /usr/bin/composer require jinxing/yii2-admin
PHP Warning:  PHP Startup: Unable to load dynamic library 'soap' (tried: /www/server/php/73/lib/php/extensions/no-debug-non-zts-20180731/soap (/www/server/php/73/lib/php/extensions/no-debug-non-zts-20180731/soap: cannot open shared object file: No such file or directory), /www/server/php/73/lib/php/extensions/no-debug-non-zts-20180731/soap.so (/www/server/php/73/lib/php/extensions/no-debug-non-zts-20180731/soap.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Using version ^1.2 for jinxing/yii2-admin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jinxing/yii2-admin 1.2.16 requires bower-asset/jinxing-tables ~1.0.0 -> no matching package found.
    - jinxing/yii2-admin 1.2.15 requires bower-asset/jinxing-tables ~1.0.0 -> no matching package found.
    - jinxing/yii2-admin 1.2.14 requires bower-asset/jinxing-tables ~1.0.0 -> no matching package found.
    - jinxing/yii2-admin 1.2.13 requires bower-asset/jinxing-tables ~1.0.0 -> no matching package found.
    - jinxing/yii2-admin 1.2.12 requires bower-asset/jinxing-tables ~1.0.0 -> no matching package found.
    - jinxing/yii2-admin 1.2.11 requires bower-asset/jinxing-tables ~1.0.0 -> no matching package found.
    - jinxing/yii2-admin 1.2.10 requires bower-asset/jinxing-tables ~1.0.0 -> no matching package found.
    - Installation request for jinxing/yii2-admin ^1.2 -> satisfiable by jinxing/yii2-admin[1.2.10, 1.2.11, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.16].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by myloveGy** [comment]
这个可能是你的composer 缓存文件问题，找不到`bower-asset/jinxing-tables` 这个包，你可以试着单独装下这个包 `composer require bower-asset/jinxing-tables`

**Comment by GordonHuangYong** [comment]
我在百度度下载的示例中,update后安装成功.
直接在新项目安装没再尝试了.
