### ISSUE TITLE
可以集成一下富文本吗？

### ISSUE THREAD

**Issue by KissWorld** [myloveGy/yii2-admin#6]
可以集成一下富文本吗？

**Comment by myloveGy** [comment]
富文本可以参考文件上传处理方式，通过自定义实现完成！后续会出一个示例

**Comment by KissWorld** [comment]
出个完全表单示例，好不好，感觉弄着好困难。

**Comment by KissWorld** [comment]
dropzone（文件拖拽上传） 配合metable封装的集成方式的也弄一个

**Comment by KissWorld** [comment]
富文本什么时候有结果呀？急急急，没有富文本，就只能原生写法，耗时费劲呀。

**Comment by myloveGy** [comment]
你加QQ群：697549103 里面有人有示例
