### ISSUE TITLE
急需富文本。

### ISSUE THREAD

**Issue by KissWorld** [myloveGy/yii2-admin#7]
富文本呀，富文本，非常需要。现在如果没有富文本只能原生写法，太费劲了。不想放弃。

**Comment by myloveGy** [comment]
你加QQ群：697549103 里面有人有示例

 

发件人: KissWorld <notifications@github.com>
答复: myloveGy/yii2-admin <reply@reply.github.com>
日期: 2020年5月22日 星期五 上午12:53
收件人: myloveGy/yii2-admin <yii2-admin@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [myloveGy/yii2-admin] 急需富文本。 (#7)

 

富文本呀，富文本，非常需要。现在如果没有富文本只能原生写法，太费劲了。不想放弃。
