### ISSUE TITLE
项目不维护了吗？compose 安装不了。几个库都不存在了

### ISSUE THREAD

**Issue by taozhipeng1990** [myloveGy/yii2-admin#9]
项目不维护了吗？compose 安装不了。几个库都不存在了
![image](https://user-images.githubusercontent.com/3894069/123721958-f66fbf00-d8b9-11eb-9976-b95b78ef7a23.png)

**Comment by myloveGy** [comment]
你换 composer 源试下

**Comment by myloveGy** [comment]
![image](https://user-images.githubusercontent.com/11523869/123725414-a34d3a80-d8c0-11eb-92a8-d59ccd9e7ddf.png)
